# Generated by Django 2.2 on 2019-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='title',
            new_name='video_link',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='artical_author',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='body',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='image',
        ),
        migrations.AddField(
            model_name='artical',
            name='video_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author4',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
