# Generated by Django 2.2 on 2019-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_gallery', '0003_auto_20190413_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
