# Generated by Django 2.2 on 2019-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_gallery', '0004_artical_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='video_link',
            field=models.CharField(default='https://www.youtube.com/embed/', max_length=200),
        ),
    ]
