# Generated by Django 2.2 on 2019-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_gallery', '0005_auto_20190413_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='image',
        ),
    ]
