# Generated by Django 2.2 on 2019-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_gallery', '0006_remove_artical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artical',
            name='video_link',
            field=models.CharField(max_length=200),
        ),
    ]
