# Generated by Django 2.2 on 2019-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='body',
            field=models.TextField(max_length=175),
        ),
    ]
