# Generated by Django 2.2 on 2019-04-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABOUT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='title',
            new_name='ngo_name',
        ),
    ]
