# Generated by Django 2.2 on 2019-04-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABOUT', '0003_our_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_team',
            old_name='image',
            new_name='member_image',
        ),
    ]
