# Generated by Django 2.2 on 2019-04-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABOUT', '0004_auto_20190409_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_team',
            old_name='Position',
            new_name='position',
        ),
    ]
